Insert datum.
jeschkies/materialize pull request #7
Opened 2022-03-07 15:40 UTC by jeschkies

This change inserts a new row for each line received.

2022-03-07 15:41 UTC, jeschkies commented on src/dataflow/src/source/loki.rs
> +                        .flat_map(|s| s.values.iter().map(|v| v.line.clone()))
I need to include the labels here.

2022-03-07 15:41 UTC, jeschkies commented on src/dataflow/src/source/loki.rs
> +                        })?;
The borrow checker is still in the way.

2022-03-07 18:12 UTC, jeschkies commented on src/dataflow/src/render/sources.rs
> +                );
This will be covered by https://github.com/jeschkies/materialize/issues/8.

2022-03-07 21:29 UTC, sd2k requested changes
Cool, excited to see this all hooked up 😁 I've left a few comments inline 👍

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
>          let client = reqwest::Client::new();
We should probably store this client in `Self` so connections are reused.

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
> +        let conn_info = conn_info;
This can be removed.

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
> +        query: String,
I _think_ this could be a `&str` which would avoid the need for the clones on line 85 :thinking: could be wrong though!

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
>              let end = SystemTime::now();
It probably doesn't matter much, but it looks like we'll end up with slightly different batch windows each iteration due to calling `now()` twice - might be better to call it once to get `end` and calculate `start` afterwards.

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
> +                end.duration_since(UNIX_EPOCH).unwrap().as_nanos(),
Would be good to replace these `unwrap`s with `expect`s :slightly_smiling_face:

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
> +                    }
We should probably be adding all of these lines at the same timestamp (i.e. as part of the same `Row`, or by using [`Timestamper::start_tx`](https://dev.materialize.com/api/rust/mz_dataflow/source/struct.Timestamper.html#method.start_tx)). Might be able to do something like...

```suggestion
                    let rows: Vec<_> = lines
                        .iter()
                        .map(|l| Datum::String(&line))
                        .collect();
                    let row = Row::pack_slice(&rows);
                    timestamper.insert(row).await.map_err(|e| SourceError {
                        source_id: self.source_id.clone(),
                        error: SourceErrorDetails::FileIO(e.to_string()),
                    })?;
```

2022-03-07 21:29 UTC, sd2k commented on src/dataflow/src/source/loki.rs
> +                        .collect();
We can avoid some allocations here using a struct:

```suggestion
                    #[derive(Debug, Serialize)]
                    struct LokiRow<'a> {
                        line: &'a str,
                        labels: &'a HashMap<String, String>,
                    }

                    let lines: Vec<String> = streams
                        .iter()
                        .flat_map(|s| {
                            s.values.iter().map(|v| {
                                serde_json::to_string(&LokiRow {
                                    line: &v.line,
                                    labels: &s.labels,
                                })
                                .unwrap()
                            })
                        })
                        .collect();
```

2022-03-08 10:17 UTC, sd2k commented
I think we might even be able to make use of some zero-copy deserialization between the Loki HTTP response and the `Datum`, but it'll require a bit of reworking of the stream code. Can be done in a separate PR after this!

2022-03-08 10:47 UTC, jeschkies commented on src/dataflow/src/source/loki.rs
>              let end = SystemTime::now();
Good catch!

2022-03-08 10:53 UTC, jeschkies commented on src/dataflow/src/source/loki.rs
> +                    }
Hm, I think this would add everything as one row.

2022-03-08 10:55 UTC, jeschkies commented on src/dataflow/src/source/loki.rs
> +        query: String,
I had to borrow `self` so that we can reuse the client.

2022-03-08 11:08 UTC, sd2k approved these changes

2022-03-08 11:09 UTC, merged